apiVersion: apps/v1
kind: Deployment

metadata:
  name: identity-api
  namespace: identity

spec:
  replicas: 3

  selector:
    matchLabels:
      app: identity-api

  template:
    metadata:
      labels:
        app: identity-api

    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/project-27f4ac7e-644c-4f16-b9b/identity-repo/identity-api:latest
          imagePullPolicy: IfNotPresent
          name: api

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: identity-api-config
            - secretRef:
                name: identity-api-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
          
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3