apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: identity-api-hpa
  namespace: identity

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity-api

  minReplicas: 3
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70