apiVersion: batch/v1
kind: Job

metadata:
  name: identity-migrate

spec:
  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: migrate
          image: migrate/migrate:4

          args:
            - "-path"
            - "/migrations"
            - "-database"
            - "$(DATABASE_URL)"
            - "up"

          envFrom:
            - secretRef:
                name: identity-api-secret

          volumeMounts:
            - name: migrations
              mountPath: /migrations

      volumes:
        - name: migrations
          configMap:
            name: identity-migrations