apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: identity

type: Opaque

stringData:
  POSTGRES_DB: "identity_db"
  POSTGRES_USER: "identity_user"
  POSTGRES_PASSWORD: "identity_password"