apiVersion: v1
kind: Secret

metadata:
  name: identity-api-secret
  namespace: identity

type: Opaque

stringData:
  JWT_SECRET: "dev-secret-change-me"
  DATABASE_URL: "postgres://identity_user:identity_password@postgres:5432/identity_db?sslmode=disable"