name: Go CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.4"

      - name: Download dependencies
        run: go mod download

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t identity-api:test .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: identity-api:test
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Debug GitHub context
        run: |
          echo "repository=${{ github.repository }}"
          echo "actor=${{ github.actor }}"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/734049747710/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@project-27f4ac7e-644c-4f16-b9b.iam.gserviceaccount.com
  
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Push Docker image to Artifact Registry
        run: |
          IMAGE=europe-west1-docker.pkg.dev/project-27f4ac7e-644c-4f16-b9b/identity-repo/identity-api

          docker tag identity-api:test $IMAGE:${{ github.sha }}
          docker tag identity-api:test $IMAGE:latest

          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
      
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: identity-cluster
          location: europe-west1
          project_id: project-27f4ac7e-644c-4f16-b9b
  
      - name: Update Kubernetes image
        run: |
          kubectl set image deployment/identity-api \
              api=europe-west1-docker.pkg.dev/project-27f4ac7e-644c-4f16-b9b/identity-repo/identity-api:${{ github.sha }} \
              -n identity
  
      - name: Wait for rollout
        run: kubectl rollout status deployment/identity-api -n identity